import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import {
	AuthInitializer,
	Navbar,
	WebSocketInitializer,
} from '@/shared/components'
import Providers from './providers'
import { Toaster } from 'react-hot-toast'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="min-h-screen bg-white text-gray-800">
					<AuthInitializer />
					<WebSocketInitializer />

					<Navbar />
					<main className="container mx-auto p-4 mt-20">
						<Providers>{children}</Providers>
					</main>
					<Toaster position="top-right" />
				</div>
			</body>
		</html>
	)
}
